// V2 Consolidated Case Study Index
// Generated by V2 consolidation process
// 31 verticals × 3 studies each (where available)

import { CaseStudyData } from "./types";
import { caseStudies } from "./index";

export interface VerticalGroup {
  vertical: string;
  studies: CaseStudyData[];
}

export const v2Verticals: VerticalGroup[] = [
  {
    vertical: "Accounting & Tax",
    studies: [
      caseStudies["accounting"],
      caseStudies["accounting-ny"],
    ],
  },
  {
    vertical: "Automotive",
    studies: [
      caseStudies["rv-dealership-phoenix"],
      caseStudies["it-managed-services-la"],
      caseStudies["travel-services"],
    ],
  },
  {
    vertical: "B2B SaaS & Tech",
    studies: [
      caseStudies["b2b-saas-national"],
      caseStudies["b2b-saas-enterprise"],
      caseStudies["ai-tool-saas-national"],
    ],
  },
  {
    vertical: "Business Services",
    studies: [
      caseStudies["franchise-development"],
      caseStudies["business-coaching-texas"],
      caseStudies["ma-advisory"],
    ],
  },
  {
    vertical: "Construction & Industrial",
    studies: [
      caseStudies["construction-membrane-materials"],
      caseStudies["electrical-supply-distribution"],
      caseStudies["commercial-construction-tx"],
    ],
  },
  {
    vertical: "Dental & Orthodontics",
    studies: [
      caseStudies["orthodontics-santa-rosa"],
      caseStudies["dental-medtech"],
      caseStudies["orthodontics-hartford"],
    ],
  },
  {
    vertical: "Ecommerce — Beauty & Skincare",
    studies: [
      caseStudies["boutique-skincare-wellness"],
      caseStudies["beauty-ecommerce-national"],
      caseStudies["hair-products-ecommerce"],
    ],
  },
  {
    vertical: "Ecommerce — Fashion & Apparel",
    studies: [
      caseStudies["ecommerce-fashion-national"],
      caseStudies["fashion-apparel"],
      caseStudies["high-end-fashion-nyc"],
    ],
  },
  {
    vertical: "Ecommerce — Health & Wellness",
    studies: [
      caseStudies["wearable-health-tech"],
      caseStudies["sports-nutrition-arizona"],
      caseStudies["wearable-health-tech-tx"],
    ],
  },
  {
    vertical: "Ecommerce — Home & Lifestyle",
    studies: [
      caseStudies["luxury-home-decor"],
      caseStudies["premium-candle-home-fragrance"],
    ],
  },
  {
    vertical: "Ecommerce — Other",
    studies: [
      caseStudies["jewelry-ecommerce"],
      caseStudies["fireworks-cincinnati"],
      caseStudies["jewelry-store-ecommerce"],
    ],
  },
  {
    vertical: "Education & Training",
    studies: [
      caseStudies["subscription-education-national"],
      caseStudies["education-chicago"],
      caseStudies["safety-training"],
    ],
  },
  {
    vertical: "Entertainment & Events",
    studies: [
      caseStudies["indoor-adventure-florida"],
      caseStudies["vr-entertainment-technology"],
      caseStudies["event-organization"],
    ],
  },
  {
    vertical: "Fitness & Wellness Services",
    studies: [
      caseStudies["fitness-equipment"],
      caseStudies["online-yoga-pilates-national"],
      caseStudies["health-wellness-app"],
    ],
  },
  {
    vertical: "Food & Beverage",
    studies: [
      caseStudies["franchise-restaurant"],
      caseStudies["packaged-foods"],
      caseStudies["restaurant-events-california"],
    ],
  },
  {
    vertical: "HVAC & Plumbing",
    studies: [
      caseStudies["hvac-vancouver"],
      caseStudies["plumbing-san-diego"],
      caseStudies["hvac-national"],
    ],
  },
  {
    vertical: "Healthcare & Medical",
    studies: [
      caseStudies["chiropractor-arizona"],
      caseStudies["medical-devices-diagnostics"],
      caseStudies["mental-health-california"],
    ],
  },
  {
    vertical: "Home Damage & Restoration",
    studies: [
      caseStudies["home-damage-restoration-florida"],
      caseStudies["home-damage-restoration"],
      caseStudies["junk-removal-los-angeles"],
    ],
  },
  {
    vertical: "Home Services",
    studies: [
      caseStudies["pool-covers-national"],
      caseStudies["custom-home-building-tennessee"],
      caseStudies["home-improvement-phoenix"],
    ],
  },
  {
    vertical: "Insurance & Financial",
    studies: [
      caseStudies["tax-planning-coaching"],
      caseStudies["fintech-new-york"],
      caseStudies["insurance-arizona"],
    ],
  },
  {
    vertical: "Landscaping & Outdoor",
    studies: [
      caseStudies["landscaping-pennsylvania"],
      caseStudies["landscaping-rc"],
      caseStudies["exterior-building-products-alabama"],
    ],
  },
  {
    vertical: "Legal Services",
    studies: [
      caseStudies["law-firm-national"],
      caseStudies["social-security-disability"],
      caseStudies["law-firm-small-practice"],
    ],
  },
  {
    vertical: "Marketing & Media",
    studies: [
      caseStudies["print-shop"],
    ],
  },
  {
    vertical: "Med Spa & Aesthetics",
    studies: [
      caseStudies["medspa-multilocation-florida"],
      caseStudies["franchise-med-spa"],
      caseStudies["multi-location-medspa-southwest"],
    ],
  },
  {
    vertical: "Moving & Logistics",
    studies: [
      caseStudies["logistics-supply-chain"],
      caseStudies["moving-company"],
      caseStudies["transportation"],
    ],
  },
  {
    vertical: "Pest Control",
    studies: [
      caseStudies["exterminator-chicago"],
      caseStudies["exterminator-ca"],
      caseStudies["exterminator"],
    ],
  },
  {
    vertical: "Real Estate",
    studies: [
      caseStudies["rental-home-management-arizona"],
      caseStudies["self-storage-new-york"],
      caseStudies["mortgage-lending"],
    ],
  },
  {
    vertical: "Roofing",
    studies: [
      caseStudies["roofing-alabama"],
      caseStudies["roofing-new-mexico"],
      caseStudies["roofing-houston"],
    ],
  },
  {
    vertical: "Security & Surveillance",
    studies: [
      caseStudies["cybersecurity"],
    ],
  },
  {
    vertical: "Staffing & Recruiting",
    studies: [
      caseStudies["remote-recruiting-national"],
      caseStudies["staffing-boston"],
    ],
  },
  {
    vertical: "Travel & Hospitality",
    studies: [
      caseStudies["private-membership-clubs"],
      caseStudies["wedding-photography-atlanta"],
      caseStudies["travel-tours"],
    ],
  },
];

// All V2 selected slugs for quick lookup
export const v2Slugs: string[] = [
  "accounting",
  "accounting-ny",
  "ai-tool-saas-national",
  "b2b-saas-enterprise",
  "b2b-saas-national",
  "beauty-ecommerce-national",
  "boutique-skincare-wellness",
  "business-coaching-texas",
  "chiropractor-arizona",
  "commercial-construction-tx",
  "construction-membrane-materials",
  "custom-home-building-tennessee",
  "cybersecurity",
  "dental-medtech",
  "ecommerce-fashion-national",
  "education-chicago",
  "electrical-supply-distribution",
  "event-organization",
  "exterior-building-products-alabama",
  "exterminator",
  "exterminator-ca",
  "exterminator-chicago",
  "fashion-apparel",
  "fintech-new-york",
  "fireworks-cincinnati",
  "fitness-equipment",
  "franchise-development",
  "franchise-med-spa",
  "franchise-restaurant",
  "hair-products-ecommerce",
  "health-wellness-app",
  "high-end-fashion-nyc",
  "home-damage-restoration",
  "home-damage-restoration-florida",
  "home-improvement-phoenix",
  "hvac-national",
  "hvac-vancouver",
  "indoor-adventure-florida",
  "insurance-arizona",
  "it-managed-services-la",
  "jewelry-ecommerce",
  "jewelry-store-ecommerce",
  "junk-removal-los-angeles",
  "landscaping-pennsylvania",
  "landscaping-rc",
  "law-firm-national",
  "law-firm-small-practice",
  "logistics-supply-chain",
  "luxury-home-decor",
  "ma-advisory",
  "medical-devices-diagnostics",
  "medspa-multilocation-florida",
  "mental-health-california",
  "mortgage-lending",
  "moving-company",
  "multi-location-medspa-southwest",
  "online-yoga-pilates-national",
  "orthodontics-hartford",
  "orthodontics-santa-rosa",
  "packaged-foods",
  "plumbing-san-diego",
  "pool-covers-national",
  "premium-candle-home-fragrance",
  "print-shop",
  "private-membership-clubs",
  "remote-recruiting-national",
  "rental-home-management-arizona",
  "restaurant-events-california",
  "roofing-alabama",
  "roofing-houston",
  "roofing-new-mexico",
  "rv-dealership-phoenix",
  "safety-training",
  "self-storage-new-york",
  "social-security-disability",
  "sports-nutrition-arizona",
  "staffing-boston",
  "subscription-education-national",
  "tax-planning-coaching",
  "transportation",
  "travel-services",
  "travel-tours",
  "vr-entertainment-technology",
  "wearable-health-tech",
  "wearable-health-tech-tx",
  "wedding-photography-atlanta"
];
